### ISSUE TITLE
Change this image on this page with new one attached

### ISSUE THREAD

**Issue by bradyredrattler** [todaycode/RedRattlerASP.NET#13]
<img width="1792" alt="Screen Shot 2021-04-01 at 1 15 52 PM" src="https://user-images.githubusercontent.com/81764176/113336757-78b50b00-92ec-11eb-9205-793e783e6e41.png">

**Comment by bradyredrattler** [comment]
Additionally, make sure to crop this image properly so that it fits the container correctly.

![seniorlivingchoicesandtypespage](https://user-images.githubusercontent.com/81764176/113336904-a8641300-92ec-11eb-851a-2b6d111b30a2.jpeg)

**Comment by onekingdev** [comment]
Done
