### ISSUE TITLE
Add this blog post

### ISSUE THREAD

**Issue by bradyredrattler** [todaycode/RedRattlerASP.NET#16]
The title of the blog is: Art and Music
https://www.dropbox.com/s/o31b8k22t79salw/Paintbrushes.jpg?dl=0
There is the cover/thumbnail photo for it ^
https://www.dropbox.com/scl/fi/3ja6qsobk2pyb89oz83pp/Art-Music.docx?dl=0&rlkey=3hbo69a0k67jgyetambs4goqz
There is the link to the content ^

**Comment by onekingdev** [comment]
I added blog statically

**Comment by onekingdev** [comment]
Right?

**Comment by onekingdev** [comment]
Done
