### ISSUE TITLE
Add this blog

### ISSUE THREAD

**Issue by bradyredrattler** [todaycode/RedRattlerASP.NET#17]
Title of blog: Should I Tour?
https://www.dropbox.com/scl/fi/hvi5r7gojmoeuc5ooklg6/Should-I-tour.docx?dl=0&rlkey=js8030iueet8btfsokjomsget
^ link to content
https://www.dropbox.com/s/348t9ngoek5cesq/shutterstock_1057007168.jpg?dl=0
^ link to thumbnail/cover photo

**Comment by onekingdev** [comment]
I added the blog statically.
