### ISSUE TITLE
Care Types missing from filter

### ISSUE THREAD

**Issue by bradyredrattler** [todaycode/RedRattlerASP.NET#24]
Here are what they are. I am pulling this screenshot from the old website. But these are the categories. Remember?
![Screen Shot 2021-04-03 at 4 45 22 PM](https://user-images.githubusercontent.com/81764176/113492319-2f0b2280-949c-11eb-8dbc-a2fb9cd64c6c.png)

**Comment by onekingdev** [comment]
I have done it, filter name is "Care Types".
