### ISSUE TITLE
Put a small border line around the bounding box so that it separates it from the background

### ISSUE THREAD

**Issue by bradyredrattler** [todaycode/RedRattlerASP.NET#26]
![Screen Shot 2021-04-03 at 4 47 23 PM](https://user-images.githubusercontent.com/81764176/113492369-827d7080-949c-11eb-991e-aa04631f9a40.png)

Here is what it looks like ^

![Screen Shot 2021-04-03 at 4 49 28 PM](https://user-images.githubusercontent.com/81764176/113492382-93c67d00-949c-11eb-90d3-a656a50f2314.png)

This is what I would like ^

**Comment by onekingdev** [comment]
I added border and background.
