### ISSUE TITLE
When hovering over the autosuggestion "San Antonio, TX" or "78232, TX" or any option that it autopopulates, it should show the clickable mouse cursor and not the typing mouse cursor

### ISSUE THREAD

**Issue by bradyredrattler** [todaycode/RedRattlerASP.NET#28]
![Screen Shot 2021-04-03 at 4 51 18 PM](https://user-images.githubusercontent.com/81764176/113492442-f9b30480-949c-11eb-8cc6-d55633385637.png)

**Comment by onekingdev** [comment]
The mouse cursor was changed to the pointer.
