### ISSUE TITLE
Products & Services page When hovering over the autosuggestion "San Antonio, TX" or "78232, TX" or any option that it autopopulates, it should show the clickable mouse cursor and not the typing mouse cursor

### ISSUE THREAD

**Issue by bradyredrattler** [todaycode/RedRattlerASP.NET#29]
![Screen Shot 2021-04-03 at 4 53 23 PM](https://user-images.githubusercontent.com/81764176/113492479-2b2bd000-949d-11eb-89d7-49eab13bd7ef.png)

**Comment by onekingdev** [comment]
I changed the mouse cursor to the pointer.
