### ISSUE TITLE
Clicking on Housing & Community Listings should direct the user to the search page

### ISSUE THREAD

**Issue by bradyredrattler** [todaycode/RedRattlerASP.NET#36]
The client said that the current landing page was part of the old website and is not part of this new website. She does not want that page to be there. She wants when people click on housing and community listings for it to go to the listings page directly. You could direct it to this https://www.seniorlivingchoices.com/communities/tx
![Screen Shot 2021-04-06 at 8 20 18 AM](https://user-images.githubusercontent.com/81764176/113717714-83d3b680-96b1-11eb-9565-85fc494c157b.png)

**Comment by onekingdev** [comment]
Done
