### ISSUE TITLE
Client added Franklin Park Alamo Heights and it is not showing on live site

### ISSUE THREAD

**Issue by bradyredrattler** [todaycode/RedRattlerASP.NET#45]
So here is the issue. The only way that it populates is if you select active adult communities. If you select any other category it does not show. See screenshots
![Screen Shot 2021-04-06 at 9 04 02 AM](https://user-images.githubusercontent.com/81764176/113724103-a072ed00-96b7-11eb-9887-de3c51ecc3d0.png)
![Screen Shot 2021-04-06 at 9 04 14 AM](https://user-images.githubusercontent.com/81764176/113724120-a537a100-96b7-11eb-9791-f432d462c42e.png)
![Screen Shot 2021-04-06 at 9 04 35 AM](https://user-images.githubusercontent.com/81764176/113724158-aff23600-96b7-11eb-9016-12c46f842fd0.png)
![Screen Shot 2021-04-06 at 9 08 35 AM](https://user-images.githubusercontent.com/81764176/113724182-b41e5380-96b7-11eb-85c4-35870206f747.png)

**Comment by justtei** [comment]
Brady PLease Provide More Details

**Comment by justtei** [comment]
BRADY ACTIVE ADULT COMMUNITES WILL ME IT TO DISPLAY IN HOUSING & COMMUNITIES AND Senior Housing & Care Will OFcourse Make it to be Diplayed in Senior Housing & Care And Active ADULT HOME WILL MAKE IT TO DISPLAY NO WHERE Except can Be REtrived From Index search As the Client Asked us to Remove it from Top Navigation Bar.

**Comment by onekingdev** [comment]
Sorry for not replying quickly.
I have seen the Upwork messages on the Email Box.
I have some problems with my computer which has an Upwork credential.
Can't I chat with Brady through skype?
And I will fix bugs as fast as possible.
