### ISSUE TITLE
New Content for Senior Living Choices & Types

### ISSUE THREAD

**Issue by bradyredrattler** [todaycode/RedRattlerASP.NET#46]
ACTIVE ADULT COMMUNITIES 55+
Active adult communities are either age-targeted or age-restricted. They offer home ownership for adults 55+. These communities are maintenance free and offer a monthly association fee. Many of these communities are single family homes, cottages, patio homes, condominiums and townhomes.

SENIOR APARTMENTS
These offer all the amenities of regular apartment communities but have a minimum age requirement, in some communities it is 55 years of age, in others it is 62. Many of these apartments offer reduced rent for those that qualify, they are identified as "affordable" apartment communities.

INDEPENDENT LIVING WITH SERVICE COMMUNITIES
These offer older adult congregate housing that is generally replete with many amenities and social activities and services. Most communities offer restaurant-style meals, frequent events and country club style furnishings.

PERSONAL CARE HOMES
This is a home in a residential care setting equipped to give adequate care to three residents. Personal care services may be delivered, i.e. assistance with bathing, moving, feeding, general oversight of the physical and mental well-being of a person who needs assistance.

ASSISTED LIVING COMMUNITIES
These offer help with all aspects of daily activities (bathing, grooming and dressing assistance, perhaps) in the atmosphere of semi-private living units. There is a wide range of services and amenities offered in this category. 

ALZHEIMER'S MEMORY CARE COMMUNITIES
These can be a special unit of a free-standing community designed to sensitively care for those with Alzheimer's or memory-related disorders.

SKILLED NURSING / PHYSICAL REHABILITATION COMMUNITIES
These offer hospital-like attention in an institutional atmosphere. These facilities offer 24-hour supervision. The amount of additional services, upkeep, food, and the structure of facilities can vary from nursing home to nursing home. They also may specialize in short term or acute nursing care, intermediate care or long term skilled nursing care.

HOSPICE CARE
Hospice care may be provided in the home or a senior care facility. Services can include pain management and a variety of emotional, spiritual and physical support issues.

HOME HEALTH CARE
Home health agencies offer skilled nursing services, wound care, distribution of medication, physical and rehabilitation therapies. 

PERSONAL CARE SERVICES
They are providers of licensed health care services in the home and communities. They offer non-medical assistance with such tasks as bathing, dressing, meal preparation and transportation.

**Comment by justtei** [comment]
Mammaaaa I was never aware of most of them 🗡️ :D

**Comment by onekingdev** [comment]
Done
