### ISSUE TITLE
Home page search needs housing types changed

### ISSUE THREAD

**Issue by bradyredrattler** [todaycode/RedRattlerASP.NET#51]
Right now if you click the dropdown it shows the current options
![Screen Shot 2021-04-08 at 11 24 11 PM](https://user-images.githubusercontent.com/81764176/114128267-9cb2b680-98c1-11eb-83a5-a5bba6832966.png)

It needs to be changed to the following options:
![Screen Shot 2021-04-08 at 11 26 19 PM](https://user-images.githubusercontent.com/81764176/114128379-da174400-98c1-11eb-82eb-79512ef8078e.png)

**Comment by onekingdev** [comment]
Done
