### ISSUE TITLE
Google Map isn't working

### ISSUE THREAD

**Issue by bradyredrattler** [todaycode/RedRattlerASP.NET#53]

**Comment by onekingdev** [comment]
Hi, Brady.

Google Maps is no longer free. You have to associate a credit card so that you can get billed if the site has requests that exceed the $200 credit they give you monthly for free.

For more information, see: https://cloud.google.com/maps-platform/pricing/

**Comment by onekingdev** [comment]
Thanks, Brady.
The key you provided works fine.
