### ISSUE TITLE
Details below property isn't showing housing type

### ISSUE THREAD

**Issue by bradyredrattler** [todaycode/RedRattlerASP.NET#54]
![Screen Shot 2021-04-08 at 11 28 19 PM](https://user-images.githubusercontent.com/81764176/114128566-3ed29e80-98c2-11eb-9170-3176d4809e47.png)
You'll see that all of the listings are displaying "55+ Community . Apartments"

This needs to actually say what type of community it is. So instead of saying "55+ Community . Apartments" it should say "Assisted Living, Alzheimer's/Memory Care" or "Physical Rehabilitation Center". Depending on what is selected as the property type on the backend of the site, it should display it there. 

Limit the amount displaying on this element to 2.

**Comment by onekingdev** [comment]
Done
