### ISSUE TITLE
Are we aware that the emails from the website are being sent from support@seniorlivingchoices.com?

### ISSUE THREAD

**Issue by bradyredrattler** [todaycode/RedRattlerASP.NET#59]
![Screen Shot 2021-04-09 at 9 24 44 AM](https://user-images.githubusercontent.com/81764176/114194831-7f0f3c80-9915-11eb-9564-be81e28851d7.png)
![Screen Shot 2021-04-09 at 9 24 54 AM](https://user-images.githubusercontent.com/81764176/114194834-7fa7d300-9915-11eb-9e25-07d2c9398eb4.png)

**Comment by justtei** [comment]
Yup Brady
