### ISSUE TITLE
From Kameron - the book number on products page on backend is missing. Ie.02057

### ISSUE THREAD

**Issue by bradyredrattler** [todaycode/RedRattlerASP.NET#61]
![image](https://user-images.githubusercontent.com/81764176/114758453-99d11f00-9d22-11eb-86d5-bb333dbb367a.png)

**Comment by justtei** [comment]
Roman.. You Need to fix it further Ko.js code is written over here too btw book was added in the model :)

**Comment by onekingdev** [comment]
Done
