### ISSUE TITLE
I am unable to sort the Products and services and the delete option button is not there. See screen shots for comparison.

### ISSUE THREAD

**Issue by bradyredrattler** [todaycode/RedRattlerASP.NET#65]
![unnamed](https://user-images.githubusercontent.com/81764176/115556961-d9de5780-a276-11eb-8da4-a513ab200b65.png)
![unnamed (1)](https://user-images.githubusercontent.com/81764176/115556977-dc40b180-a276-11eb-8d42-8916db899b58.png)

**Comment by justtei** [comment]
Brady What does Kameron Mean y Sorting I have tested Filter the sorting was perfect.
