### ISSUE TITLE
Please and Sorry We can now follow old design which was present in search page for new template

### ISSUE THREAD

**Issue by justtei** [todaycode/RedRattlerASP.NET#9]
And we may also have to fix this problem

![image](https://user-images.githubusercontent.com/45319706/112534746-4592e900-8dcd-11eb-8656-4cccd88b9eef.png)

**Comment by onekingdev** [comment]
sorry, I don't understand your needs well.
Do you want an old version style? Or PSD style?
Which one? Two styles are followed.
![image](https://user-images.githubusercontent.com/80197196/112538756-4291fb80-8dc1-11eb-831b-c341b1528a25.png)

![image](https://user-images.githubusercontent.com/80197196/112538912-6d7c4f80-8dc1-11eb-9bd3-3a735471f10b.png)

**Comment by justtei** [comment]
That's Great Roman We just want it to follow UI again.

**Comment by onekingdev** [comment]
I see, the title is removed on UI?
![Screenshot 2021-03-26 002731](https://user-images.githubusercontent.com/80197196/112546179-2cd50400-8dca-11eb-9f33-719e7b086ce3.png)
Is this what you want?

**Comment by justtei** [comment]
yup <3
